<?php

date_default_timezone_set('Asia/Jakarta');

require 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$image = $_POST['image'] ?? '';
$plant = $_POST['plant'] ?? '-';
$confidence = $_POST['confidence'] ?? '-';
$status = $_POST['status'] ?? '-';
$advice = $_POST['advice'] ?? '-';

// $date = date("d M Y H:i");

$date = date("d F Y, H:i") . " WIB";

$options = new Options();
$options->set('isRemoteEnabled', true);

$pdf = new Dompdf($options);

$html = "

<style>

body{
font-family:Arial;
padding:35px;
color:#333;
}

.header{
text-align:center;
margin-bottom:30px;
}

.header h1{
color:#2f9e44;
margin:0;
font-size:34px;
}

.header p{
color:#666;
}

.card{
background:#f8f9fa;
padding:25px;
border-radius:20px;
}

.image-wrap{
text-align:center;
margin-bottom:25px;
}

img{
width:420px;
max-width:100%;
border-radius:18px;
}

table{
width:100%;
border-collapse:collapse;
}

td{
padding:14px;
border-bottom:1px solid #ddd;
}

.label{
font-weight:bold;
background:#edf5ed;
width:180px;
}

.footer{
margin-top:40px;
text-align:center;
font-size:12px;
color:#777;
}

</style>

<div class='header'>
<h1>FARMOGANA REPORT</h1>
<p>Smart Agriculture Diagnosis Report</p>
</div>

<div class='card'>

<div class='image-wrap'>
<img src='$image'>
</div>

<table>

<tr>
<td class='label'>Plant</td>
<td>$plant</td>
</tr>

<tr>
<td class='label'>Confidence</td>
<td>$confidence%</td>
</tr>

<tr>
<td class='label'>Status</td>
<td>$status</td>
</tr>

<tr>
<td class='label'>Diagnosis</td>
<td>$advice</td>
</tr>

<tr>
<td class='label'>Scan Date</td>
<td>$date</td>
</tr>

</table>

</div>

<div class='footer'>
Generated by Farmogana
</div>

";

$pdf->loadHtml($html);

$pdf->setPaper('A4');

$pdf->render();

$pdf->stream(
"hasil.pdf",
["Attachment"=>true]
);